### ISSUE TITLE
Investigate the following scenario: bind class to singleton, and bind protocol to the class. Currently it returns `nil`.

### ISSUE THREAD

**Issue by Przytua** [ApplauseOSS/Swifjection#29]

**Comment by Przytua** [comment]
@azubala This is covered in specs: `SwifjectionIntegrationTests` `"when type is bound to other type"` `"and the bound type is bound as singleton"`. Please confirm and close the issue.

**Comment by azubala** [comment]
I couldn't make it work in real life scenario in our app -- I will investigate.

**Comment by azubala** [comment]
This was my mistake, I flipped arguments when binding protocol to type. Instead of:
```
bind(type: MyClass.self, toType: MyProtocol.self)
```

I did:
```
bind(type: MyProtocol.self, toType: MyClass.self)
```
